### ISSUE TITLE
About swaylock executable location

### ISSUE THREAD

**Issue by ivanottantuno** [jirutka/swaylockd#1]
Hi,
I've compiled your program on debian 11 bullseye but as you know swaylock is removed.
I have to modify the swaylock executable location from `/usr/bin/swaylock` to `/usr/local/bin/swaylock` in `swaylockd.c` and in `Makefile` because I compiled swaylock from the git repo sources and I have installed it here.
So what I suggest you is to put a control of the location of the executable of swaylock instead of the absolute location.
Best regards

**Comment by jirutka** [comment]
It is configurable on build time – look at [SWAYLOCK_PATH](https://github.com/jirutka/swaylockd/blob/441afb1e41e0f6e8ae0f0a9aed7555029bad6f62/Makefile#L9) in Makefile.

I assume that you have used the prebuilt binary, right?

**Comment by ivanottantuno** [comment]
Yes it's my fault, sorry.
No, I compile from source.
