### ISSUE TITLE
Use `--screenshots` at multi-monitor display,

### ISSUE THREAD

**Issue by awarewen** [jirutka/swaylockd#2]
Using the `--screenshots` parameter in the case of multiple monitors the screenshot background on the second screen only shows the screenshot of the first screen, and the screenshot is shown in the wrong resolution.

Version:
swaylockd version 0.1.0
swaylock version v1.6.11 (Apr 30 2023, branch 'master')

wm: hyprland-git r2890.a31dceb2-1

OS: arch linux

-- monitor 1： 1920x1200
-- monitor 2 :  3840x2180

Command:
`$ swaylockd --screenshots`

![Image_5601863](https://user-images.githubusercontent.com/53365857/236867085-9caa02f3-009e-49f0-8291-211a350765f1.jpg)

**Comment by jirutka** [comment]
This has nothing to do with swaylockd, it’s just a launcher.

> A dumb launcher to spawn swaylock and ensure it runs no matter what
